name: Continues Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-test:
    name: Run CI checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYTHON_VERSION:
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
      - name: Setup poetry
        uses: Gr1N/setup-poetry@v8
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        run: |
          poetry install
      - name: Run isort
        run: |
          poetry run isort . --check
      - name: Run black
        run: |
          poetry run black --check --diff .
      - name: Run flake8
        run: |
          poetry run flake8 .
      - name: Run pytest
        run: |
          poetry run pytest --cov=pseud --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
